#
# Module manifest for module 'PSLogger'
#
# Generated by: Mark Newton
#
# Generated on: 08/15/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PSLogger.psm1'

# Version number of this module.
ModuleVersion = '1.0.0'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = 'a8b4c6d8-1e2f-4a5b-9c7d-3f8e2b1a6d4c'

# Author of this module
Author = 'Mark Newton'

# Company or vendor of this module
CompanyName = 'Aunalytics Managed Services'

# Copyright statement for this module
Copyright = '(c) 2025 Mark Newton. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Advanced PowerShell logging module with enrichers, handlers, filters, and scoped properties. Provides enterprise-grade logging with automatic rotation, compression, multiple output targets, structured logging (JSON), correlation IDs, lazy string formatting, exception logging, and comprehensive context tracking.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.0'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.5'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
CLRVersion = '4.0'

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    # Core logger initialization and management
    'Initialize-Log',
    'New-Logger',
    'Get-Logger',
    'Set-DefaultLogger',
    'Get-DefaultLogger',

    # Primary logging functions
    'Write-Log',
    'Write-LogInfo',
    'Write-LogWarning',
    'Write-LogError',
    'Write-LogCritical',
    'Write-LogDebug',
    'Write-LogSuccess',

    # Logger information and testing
    'Get-LoggerInfo',
    'Test-Logger',

    # Enricher management
    'Add-LogEnricher',
    'New-MachineEnricher',
    'New-ProcessEnricher',
    'New-ThreadEnricher',
    'New-EnvironmentEnricher',
    'New-NetworkEnricher',

    # Handler management
    'Add-LogHandler',
    'New-FileHandler',
    'New-ConsoleHandler',
    'New-EventLogHandler',
    'New-NullHandler',

    # Filter management
    'Add-LogFilter',
    'New-FunctionFilter',
    'New-TimeFilter',
    'New-UserFilter',

    # Scoped properties
    'Start-LogScope'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = @(
    'PSLogger.psm1',
    'PSLogger.psd1',
    'README.md'
)

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @(
            'Logging',
            'Log',
            'Logger',
            'Audit',
            'Monitoring',
            'Diagnostics',
            'Troubleshooting',
            'Enterprise',
            'Rotation',
            'Compression',
            'Enrichers',
            'Handlers',
            'Filters',
            'StructuredLogging',
            'JSON',
            'EventLog',
            'SIEM',
            'Windows',
            'PSEdition_Desktop',
            'PSEdition_Core'
        )

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'
## Version 1.0.0 - Initial Release (2025-11-05)

CORE FEATURES:
- Multiple log levels (INFO, WARNING, ERROR, DEBUG, CRITICAL, SUCCESS)
- Automatic log rotation (size-based, age-based, time-based patterns)
- Log compression with ZIP archiving and retention policies
- Color-coded console output with flexible formatting
- Retry mechanism for file write operations with configurable delays
- Support for multiple concurrent loggers
- Path validation and security checks
- Disk space monitoring before write operations
- Thread-safe operations with mutex protection

ADVANCED FEATURES:
- Structured Logging: JSON output for SIEM integration (Splunk, ELK, Azure Monitor)
- Enrichers: 5 built-in enrichers for automatic context injection (Machine, Process, Thread, Environment, Network)
- Handlers: 4 output targets (File, Console, Windows Event Log, Null)
- Filters: 3 conditional filters (Time-based, Function-based, User-based)
- Correlation IDs: Distributed tracing support with automatic GUID generation
- Lazy String Formatting: 30x performance improvement for filtered logs
- Exception Logging: Full stack traces with inner exceptions and HResult
- Scoped Properties: Hierarchical context tracking with IDisposable pattern
- Buffered Writes: 30x faster batch operations for high-volume logging
- Log Sampling: 90-99% volume reduction for high-throughput scenarios
- Time-Based Rotation: Daily, weekly, monthly patterns with custom intervals
- Safe Archive Rotation: Prevents data loss during compression operations

HELPER FUNCTIONS (24 total):
- Logger Management: New-Logger, Get-Logger, Set-DefaultLogger, Get-DefaultLogger
- Enricher Functions: Add-LogEnricher, New-MachineEnricher, New-ProcessEnricher, New-ThreadEnricher, New-EnvironmentEnricher, New-NetworkEnricher
- Handler Functions: Add-LogHandler, New-FileHandler, New-ConsoleHandler, New-EventLogHandler, New-NullHandler
- Filter Functions: Add-LogFilter, New-FunctionFilter, New-TimeFilter, New-UserFilter
- Scoped Properties: Start-LogScope
'@

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}